// Mock data - Replace with API calls later
export const mockFields = [
  {
    id: 1,
    name: "Wheat Field A",
    cropType: "Wheat",
    plantingDate: "2026-02-15",
    currentStage: "Growing",
    status: "Active",
    notes: "",
    agent: "John Smith",
    lastUpdate: "2 hours ago",
  },
  {
    id: 2,
    name: "Corn Plot 2",
    cropType: "Corn",
    plantingDate: "2026-02-20",
    currentStage: "Growing",
    status: "At Risk",
    notes: "Insufficient water - needs irrigation",
    agent: "Sarah Johnson",
    lastUpdate: "1 hour ago",
  },
  {
    id: 3,
    name: "Rice Field East",
    cropType: "Rice",
    plantingDate: "2026-02-10",
    currentStage: "Growing",
    status: "Active",
    notes: "",
    agent: "Mike Chen",
    lastUpdate: "30 minutes ago",
  },
  {
    id: 4,
    name: "Barley North",
    cropType: "Barley",
    plantingDate: "2026-02-18",
    currentStage: "Ready",
    status: "Completed",
    notes: "",
    agent: "Emma Wilson",
    lastUpdate: "3 hours ago",
  },
  {
    id: 5,
    name: "Soybean West",
    cropType: "Soybean",
    plantingDate: "2026-02-05",
    currentStage: "Ready",
    status: "Completed",
    notes: "",
    agent: "John Smith",
    lastUpdate: "5 hours ago",
  },
  {
    id: 6,
    name: "Wheat Field B",
    cropType: "Wheat",
    plantingDate: "2026-02-25",
    currentStage: "Planted",
    status: "Active",
    notes: "",
    agent: "Sarah Johnson",
    lastUpdate: "1 day ago",
  },
  {
    id: 7,
    name: "Corn Plot 1",
    cropType: "Corn",
    plantingDate: "2026-01-30",
    currentStage: "Ready",
    status: "At Risk",
    notes: "Pest infestation detected - requires treatment",
    agent: "Mike Chen",
    lastUpdate: "1 day ago",
  },
];
